org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=blade_tetra
mod_name=Blade Tetra: Forged Styles
mod_license=MIT
mod_version=1.1.1
mod_group_id=dev.bladetetra
mod_authors=Blade Tetra Team
mod_description=Material-crafted modular SlashBlade combat for Tetra and SlashBlade: Resharped.

tetra_file_id=6848811
mutil_version=1.20.1-6.2.0
slashblade_resharped_file_id=8018222
player_anim_version=1.0.2-rc1+1.20
